sonar.projectKey=GeraldineBecerra_Ingenieria_devops
sonar.organization=geraldinebecerra

sonar.projectName=Ingenieria_devops
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=__tests__

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.scanner.skipJreProvisioning=true

sonar.exclusions=node_modules/**,dist/**,coverage/**,**/*.test.ts,**/*.test.tsx
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.sourceEncoding=UTF-8
